name: CI/CD - Flask Docker App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.CLOUDMASUSER }}/flask-docker-app:latest .

    # 4. Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.CLOUDMASUSER }}" --password-stdin

    # 5. Push Docker image
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.CLOUDMASUSER }}/flask-docker-app:latest

    # 6. Deploy to AWS EC2
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.CLOUDMASUSER }}/flask-docker-app:latest
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d -p 5000:5000 --name flask-app ${{ secrets.CLOUDMASUSER }}/flask-docker-app:latest
