name: CI - Build and Test Docker Flask App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t flask-docker-app .

    - name: Run container
      run: docker run -d -p 5000:5000 --name flask-test flask-docker-app

    - name: Show container logs
      run: docker logs flask-test
